### ISSUE TITLE
option to override range for non-powered magic staves

### ISSUE THREAD

**Issue by MammothJerk** [tylerwgrass/attack-ranges#1]
Really cool plugin!

One thing i noticed right away is if i'm holding a kodai wand without autocast selected the attack range for magic is not shown. 

I would suggest an override in the settings like "handle staves as magic-range" that would show the magic attack range on common non-powered magic weapons such as staff of the dead, toxic staff of the dead, kodai wand, ancient sceptres, nightmare staffs, etc.

It might be easier to create a list of excluded [weapon slots](https://oldschool.runescape.wiki/w/Weapon_slot_table) with magic attack bonus instead of manually adding all staves. then excluding stuff like all daggers, voidwaker, and blisterwood flail(i know some people use it for pking as a magic staff but i think its mostly used as a melee weapon.)

Thanks!

**Comment by tylerwgrass** [comment]
Curious why you would want this.  If you forget to select a spell (or your stats change/ you run out of runes) and go to cast thinking you aren't because the lines are there, you'll get dragged around.

**Comment by tylerwgrass** [comment]
I think I understand after reading some other comments. 

If this is you want to show the area anyways in case you are manually casting, I've added it here: 016ee06fb6897e800ce065984a06b1b81315e204
