### ISSUE TITLE
Tokzt-kil-ul missing

### ISSUE THREAD

**Issue by andersenalan** [tylerwgrass/attack-ranges#16]
Hi @tylerwgrass! I've noticed recently that Toktz-xil-ul (id 6522) is missing. The wiki describes it as "having stats equivalent to a magic shortbow in conjunction with rune arrows." It does have a range of 7 (+2 for long range) like shortbows but that doesn't really feel like the proper category when non-standard thrown is available. Looking for your thoughts. I'm happy to create a PR if you are open to contributors. Thanks

**Comment by tylerwgrass** [comment]
thanks for the report, I've fixed it and will close when it is merged into the plugin hub.
