### ISSUE TITLE
Missing weapons

### ISSUE THREAD

**Issue by MammothJerk** [tylerwgrass/attack-ranges#2]
Just went through most of the weapons in my bank and i found these missing 😁 

Tonalztics of ralos
Accursed sceptre (a) - is in essence a melee weapon when autocasting is not enabled but range shows as the powered staff version (non (a))
venator bow
crystal bow
crystal halberd - i'm assuming all halberds are missing
tecu salamander - I'm assuming all salamanders are missing - They can attack diagonally so it might warrant being added but i doubt it 😁

**Comment by tylerwgrass** [comment]
I was sure I'd missed some, thanks!

**Comment by tylerwgrass** [comment]
Fixed with e54c81f
